---
gui:
  border: rounded
  showBottomLine: false
  theme:
    activeBorderColor: [cyan, bold]
    inactiveBorderColor: [white]
    optionsTextColor: [blue]
    selectedLineBgColor: [default]
    selectedRangeBgColor: [blue]
keybinding:
  universal:
    undo: u
    redo: <c-r>
