---
# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --syntax-theme="TwoDark"
  branchLogCmd: git log --color --graph --pretty=format:'%Cred%h%Creset - %C(bold blue)%an,%Creset %Cgreen%cr%C(yellow)%d%Creset, %s' --abbrev-commit {{branchName}} --
gui:
  border: rounded
  showBottomLine: false
  theme:
    activeBorderColor: [cyan, bold]
    inactiveBorderColor: [white]
    optionsTextColor: [blue]
    selectedLineBgColor: [blue]
notARepository: skip # one of: 'prompt' | 'create' | 'skip' | 'quit'
keybinding:
  universal:
    undo: u
    redo: <c-r>
customCommands:
  - key: b
    command: tig blame -- {{.SelectedFile.Name}}
    context: files
    description: blame file at tree
    subprocess: true
  - key: b
    command: tig blame {{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: blame file at revision
    subprocess: true
  - key: B
    command: tig blame -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: blame file at tree
    subprocess: true
