---
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --syntax-theme="TwoDark"
gui:
  border: rounded
  showBottomLine: false
  theme:
    activeBorderColor: [cyan, bold]
    inactiveBorderColor: [white]
    optionsTextColor: [blue]
    selectedLineBgColor: [default]
    selectedRangeBgColor: [blue]
keybinding:
  universal:
    undo: u
    redo: <c-r>
